=begin
#Etsy Open API v3

#<div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/issues/new/choose\">please add an issue in Github</a>.</p></div>&copy; 2021-2022 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

The version of the OpenAPI document: 3.0.0
Contact: developers@etsy.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.1

=end

require 'date'
require 'time'

module EtsyApi
  # List of refund objects on an Etsy Payments transaction. All monetary amounts are in USD pennies unless otherwise specified.
  class PaymentAccountLedgerEntryPaymentAdjustmentsInner
    # The numeric ID for a payment adjustment.
    attr_accessor :payment_adjustment_id

    # A unique numeric ID for a payment to a specific Etsy [shop](/documentation/reference#tag/Shop).
    attr_accessor :payment_id

    # The status string of the payment adjustment.
    attr_accessor :status

    # When true, the payment adjustment was or is likely to complete successfully.
    attr_accessor :is_success

    # The numeric ID for the [user](/documentation/reference#tag/User) (seller) fulfilling the purchase.
    attr_accessor :user_id

    # A human-readable string describing the reason for the refund.
    attr_accessor :reason_code

    # The total numeric amount of the refund in the payment currency.
    attr_accessor :total_adjustment_amount

    # The numeric amount of the refund in the shop currency.
    attr_accessor :shop_total_adjustment_amount

    # The numeric amount of the refund in the buyer currency.
    attr_accessor :buyer_total_adjustment_amount

    # The numeric amount of card processing fees associated with a payment adjustment.
    attr_accessor :total_fee_adjustment_amount

    # The transaction\\'s creation date and time, in epoch seconds.
    attr_accessor :create_timestamp

    # The transaction\\'s creation date and time, in epoch seconds.
    attr_accessor :created_timestamp

    # The date and time of the last change to the payment adjustment in epoch seconds.
    attr_accessor :update_timestamp

    # The date and time of the last change to the payment adjustment in epoch seconds.
    attr_accessor :updated_timestamp

    # List of payment adjustment line items.
    attr_accessor :payment_adjustment_items

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'payment_adjustment_id' => :'payment_adjustment_id',
        :'payment_id' => :'payment_id',
        :'status' => :'status',
        :'is_success' => :'is_success',
        :'user_id' => :'user_id',
        :'reason_code' => :'reason_code',
        :'total_adjustment_amount' => :'total_adjustment_amount',
        :'shop_total_adjustment_amount' => :'shop_total_adjustment_amount',
        :'buyer_total_adjustment_amount' => :'buyer_total_adjustment_amount',
        :'total_fee_adjustment_amount' => :'total_fee_adjustment_amount',
        :'create_timestamp' => :'create_timestamp',
        :'created_timestamp' => :'created_timestamp',
        :'update_timestamp' => :'update_timestamp',
        :'updated_timestamp' => :'updated_timestamp',
        :'payment_adjustment_items' => :'payment_adjustment_items'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'payment_adjustment_id' => :'Integer',
        :'payment_id' => :'Integer',
        :'status' => :'String',
        :'is_success' => :'Boolean',
        :'user_id' => :'Integer',
        :'reason_code' => :'String',
        :'total_adjustment_amount' => :'Integer',
        :'shop_total_adjustment_amount' => :'Integer',
        :'buyer_total_adjustment_amount' => :'Integer',
        :'total_fee_adjustment_amount' => :'Integer',
        :'create_timestamp' => :'Integer',
        :'created_timestamp' => :'Integer',
        :'update_timestamp' => :'Integer',
        :'updated_timestamp' => :'Integer',
        :'payment_adjustment_items' => :'Array<PaymentAdjustmentPaymentAdjustmentItemsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'total_adjustment_amount',
        :'shop_total_adjustment_amount',
        :'buyer_total_adjustment_amount',
        :'total_fee_adjustment_amount',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'PaymentAdjustment'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `EtsyApi::PaymentAccountLedgerEntryPaymentAdjustmentsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `EtsyApi::PaymentAccountLedgerEntryPaymentAdjustmentsInner`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'payment_adjustment_id')
        self.payment_adjustment_id = attributes[:'payment_adjustment_id']
      end

      if attributes.key?(:'payment_id')
        self.payment_id = attributes[:'payment_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'is_success')
        self.is_success = attributes[:'is_success']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'reason_code')
        self.reason_code = attributes[:'reason_code']
      end

      if attributes.key?(:'total_adjustment_amount')
        self.total_adjustment_amount = attributes[:'total_adjustment_amount']
      end

      if attributes.key?(:'shop_total_adjustment_amount')
        self.shop_total_adjustment_amount = attributes[:'shop_total_adjustment_amount']
      end

      if attributes.key?(:'buyer_total_adjustment_amount')
        self.buyer_total_adjustment_amount = attributes[:'buyer_total_adjustment_amount']
      end

      if attributes.key?(:'total_fee_adjustment_amount')
        self.total_fee_adjustment_amount = attributes[:'total_fee_adjustment_amount']
      end

      if attributes.key?(:'create_timestamp')
        self.create_timestamp = attributes[:'create_timestamp']
      end

      if attributes.key?(:'created_timestamp')
        self.created_timestamp = attributes[:'created_timestamp']
      end

      if attributes.key?(:'update_timestamp')
        self.update_timestamp = attributes[:'update_timestamp']
      end

      if attributes.key?(:'updated_timestamp')
        self.updated_timestamp = attributes[:'updated_timestamp']
      end

      if attributes.key?(:'payment_adjustment_items')
        if (value = attributes[:'payment_adjustment_items']).is_a?(Array)
          self.payment_adjustment_items = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@payment_adjustment_id.nil? && @payment_adjustment_id < 1
        invalid_properties.push('invalid value for "payment_adjustment_id", must be greater than or equal to 1.')
      end

      if !@payment_id.nil? && @payment_id < 1
        invalid_properties.push('invalid value for "payment_id", must be greater than or equal to 1.')
      end

      if !@user_id.nil? && @user_id < 1
        invalid_properties.push('invalid value for "user_id", must be greater than or equal to 1.')
      end

      if !@total_adjustment_amount.nil? && @total_adjustment_amount < 0
        invalid_properties.push('invalid value for "total_adjustment_amount", must be greater than or equal to 0.')
      end

      if !@shop_total_adjustment_amount.nil? && @shop_total_adjustment_amount < 0
        invalid_properties.push('invalid value for "shop_total_adjustment_amount", must be greater than or equal to 0.')
      end

      if !@buyer_total_adjustment_amount.nil? && @buyer_total_adjustment_amount < 0
        invalid_properties.push('invalid value for "buyer_total_adjustment_amount", must be greater than or equal to 0.')
      end

      if !@total_fee_adjustment_amount.nil? && @total_fee_adjustment_amount < 0
        invalid_properties.push('invalid value for "total_fee_adjustment_amount", must be greater than or equal to 0.')
      end

      if !@create_timestamp.nil? && @create_timestamp < 946684800
        invalid_properties.push('invalid value for "create_timestamp", must be greater than or equal to 946684800.')
      end

      if !@created_timestamp.nil? && @created_timestamp < 946684800
        invalid_properties.push('invalid value for "created_timestamp", must be greater than or equal to 946684800.')
      end

      if !@update_timestamp.nil? && @update_timestamp < 946684800
        invalid_properties.push('invalid value for "update_timestamp", must be greater than or equal to 946684800.')
      end

      if !@updated_timestamp.nil? && @updated_timestamp < 946684800
        invalid_properties.push('invalid value for "updated_timestamp", must be greater than or equal to 946684800.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@payment_adjustment_id.nil? && @payment_adjustment_id < 1
      return false if !@payment_id.nil? && @payment_id < 1
      return false if !@user_id.nil? && @user_id < 1
      return false if !@total_adjustment_amount.nil? && @total_adjustment_amount < 0
      return false if !@shop_total_adjustment_amount.nil? && @shop_total_adjustment_amount < 0
      return false if !@buyer_total_adjustment_amount.nil? && @buyer_total_adjustment_amount < 0
      return false if !@total_fee_adjustment_amount.nil? && @total_fee_adjustment_amount < 0
      return false if !@create_timestamp.nil? && @create_timestamp < 946684800
      return false if !@created_timestamp.nil? && @created_timestamp < 946684800
      return false if !@update_timestamp.nil? && @update_timestamp < 946684800
      return false if !@updated_timestamp.nil? && @updated_timestamp < 946684800
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_adjustment_id Value to be assigned
    def payment_adjustment_id=(payment_adjustment_id)
      if !payment_adjustment_id.nil? && payment_adjustment_id < 1
        fail ArgumentError, 'invalid value for "payment_adjustment_id", must be greater than or equal to 1.'
      end

      @payment_adjustment_id = payment_adjustment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] payment_id Value to be assigned
    def payment_id=(payment_id)
      if !payment_id.nil? && payment_id < 1
        fail ArgumentError, 'invalid value for "payment_id", must be greater than or equal to 1.'
      end

      @payment_id = payment_id
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if !user_id.nil? && user_id < 1
        fail ArgumentError, 'invalid value for "user_id", must be greater than or equal to 1.'
      end

      @user_id = user_id
    end

    # Custom attribute writer method with validation
    # @param [Object] total_adjustment_amount Value to be assigned
    def total_adjustment_amount=(total_adjustment_amount)
      if !total_adjustment_amount.nil? && total_adjustment_amount < 0
        fail ArgumentError, 'invalid value for "total_adjustment_amount", must be greater than or equal to 0.'
      end

      @total_adjustment_amount = total_adjustment_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] shop_total_adjustment_amount Value to be assigned
    def shop_total_adjustment_amount=(shop_total_adjustment_amount)
      if !shop_total_adjustment_amount.nil? && shop_total_adjustment_amount < 0
        fail ArgumentError, 'invalid value for "shop_total_adjustment_amount", must be greater than or equal to 0.'
      end

      @shop_total_adjustment_amount = shop_total_adjustment_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] buyer_total_adjustment_amount Value to be assigned
    def buyer_total_adjustment_amount=(buyer_total_adjustment_amount)
      if !buyer_total_adjustment_amount.nil? && buyer_total_adjustment_amount < 0
        fail ArgumentError, 'invalid value for "buyer_total_adjustment_amount", must be greater than or equal to 0.'
      end

      @buyer_total_adjustment_amount = buyer_total_adjustment_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] total_fee_adjustment_amount Value to be assigned
    def total_fee_adjustment_amount=(total_fee_adjustment_amount)
      if !total_fee_adjustment_amount.nil? && total_fee_adjustment_amount < 0
        fail ArgumentError, 'invalid value for "total_fee_adjustment_amount", must be greater than or equal to 0.'
      end

      @total_fee_adjustment_amount = total_fee_adjustment_amount
    end

    # Custom attribute writer method with validation
    # @param [Object] create_timestamp Value to be assigned
    def create_timestamp=(create_timestamp)
      if !create_timestamp.nil? && create_timestamp < 946684800
        fail ArgumentError, 'invalid value for "create_timestamp", must be greater than or equal to 946684800.'
      end

      @create_timestamp = create_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] created_timestamp Value to be assigned
    def created_timestamp=(created_timestamp)
      if !created_timestamp.nil? && created_timestamp < 946684800
        fail ArgumentError, 'invalid value for "created_timestamp", must be greater than or equal to 946684800.'
      end

      @created_timestamp = created_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] update_timestamp Value to be assigned
    def update_timestamp=(update_timestamp)
      if !update_timestamp.nil? && update_timestamp < 946684800
        fail ArgumentError, 'invalid value for "update_timestamp", must be greater than or equal to 946684800.'
      end

      @update_timestamp = update_timestamp
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_timestamp Value to be assigned
    def updated_timestamp=(updated_timestamp)
      if !updated_timestamp.nil? && updated_timestamp < 946684800
        fail ArgumentError, 'invalid value for "updated_timestamp", must be greater than or equal to 946684800.'
      end

      @updated_timestamp = updated_timestamp
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          payment_adjustment_id == o.payment_adjustment_id &&
          payment_id == o.payment_id &&
          status == o.status &&
          is_success == o.is_success &&
          user_id == o.user_id &&
          reason_code == o.reason_code &&
          total_adjustment_amount == o.total_adjustment_amount &&
          shop_total_adjustment_amount == o.shop_total_adjustment_amount &&
          buyer_total_adjustment_amount == o.buyer_total_adjustment_amount &&
          total_fee_adjustment_amount == o.total_fee_adjustment_amount &&
          create_timestamp == o.create_timestamp &&
          created_timestamp == o.created_timestamp &&
          update_timestamp == o.update_timestamp &&
          updated_timestamp == o.updated_timestamp &&
          payment_adjustment_items == o.payment_adjustment_items
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [payment_adjustment_id, payment_id, status, is_success, user_id, reason_code, total_adjustment_amount, shop_total_adjustment_amount, buyer_total_adjustment_amount, total_fee_adjustment_amount, create_timestamp, created_timestamp, update_timestamp, updated_timestamp, payment_adjustment_items].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = EtsyApi.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
